import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import openapiTS from "openapi-typescript";

async function readStdin() {
  const chunks = [];

  if (process.stdin.isTTY) {
    throw new Error("Expected OpenAPI JSON on stdin");
  }

  for await (const chunk of process.stdin) {
    chunks.push(Buffer.from(chunk));
  }

  return Buffer.concat(chunks).toString("utf8");
}

async function main() {
  const args = process.argv.slice(2);
  let outPath;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--out") {
      outPath = args[index + 1];
      index += 1;
      if (!outPath) {
        throw new Error("--out requires a path");
      }
      continue;
    }

    if (arg === "--help" || arg === "-h") {
      printHelp();
      return;
    }

    throw new Error(`Unrecognised argument '${arg}'. Run with --help for usage.`);
  }

  if (!outPath) {
    throw new Error("Missing required --out argument");
  }

  const raw = await readStdin();
  const spec = JSON.parse(raw);

  const generated = await openapiTS(spec, {
    exportType: true,
  });

  const schemaAliases = Object.keys(spec?.components?.schemas ?? {}).map((name) =>
    `export type ${name} = components["schemas"]["${name}"];`,
  );

  const header = `/**
 * This file is automatically generated from the server OpenAPI schema.
 * Do not edit this file directly; run \`pnpm --dir web generate:api\` instead.
 */\n`;
  const aliasBlock = schemaAliases.length
    ? `\n// Re-export individual schema types for ease of use.\n${schemaAliases.join("\n")}\n`
    : "";

  const contents = `${header}${generated.trim()}\n${aliasBlock}`;

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, contents, "utf8");
}

function printHelp() {
  console.log(`Generate TypeScript definitions for the crep-server API.\n\n\
Usage: generate-types --out <path>\n\n\
This command expects the OpenAPI JSON on stdin.`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
