/**
 * This file is automatically generated from the server OpenAPI schema.
 * Do not edit this file directly; run `pnpm --dir web generate:api` instead.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = {
  "/api/search": {
    post: operations["search"];
  };
};

export type webhooks = Record<string, never>;

export type components = {
  schemas: {
    ErrorResponse: {
      message: string;
    };
    LineHighlight: {
      column: number;
      term: string;
    };
    LineMatch: {
      content: string;
      highlights: components["schemas"]["LineHighlight"][];
      line_number: number;
    };
    MatchDetail: {
      commit_date: string;
      /** Format: int32 */
      commit_index: number;
      commit_sha: string;
      commit_summary: string;
      lines: components["schemas"]["LineMatch"][];
    };
    SearchHit: {
      file_path: string;
      first_match: components["schemas"]["MatchDetail"];
      last_match?: null | components["schemas"]["MatchDetail"];
    };
    /** @enum {string} */
    SearchMode: "plain" | "regex";
    SearchRequest: {
      limit?: number | null;
      mode?: components["schemas"]["SearchMode"];
      query: string;
    };
    SearchResponse: {
      results: components["schemas"]["SearchHit"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = {

  search: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchRequest"];
      };
    };
    responses: {
      /** @description Search results */
      200: {
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      /** @description Invalid query */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
};

// Re-export individual schema types for ease of use.
export type ErrorResponse = components["schemas"]["ErrorResponse"];
export type LineHighlight = components["schemas"]["LineHighlight"];
export type LineMatch = components["schemas"]["LineMatch"];
export type MatchDetail = components["schemas"]["MatchDetail"];
export type SearchHit = components["schemas"]["SearchHit"];
export type SearchMode = components["schemas"]["SearchMode"];
export type SearchRequest = components["schemas"]["SearchRequest"];
export type SearchResponse = components["schemas"]["SearchResponse"];
