/**
 * This file is automatically generated from the server OpenAPI schema.
 * Do not edit this file directly; run `pnpm --dir web generate:api` instead.
 */
export type paths = {
  "/api/search": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SearchRequest"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["SearchResponse"];
          };
          description: "Search results";
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
          description: "Invalid query";
        };
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
          description: "Internal server error";
        };
      };
    };
  };
};

export type components = {
  schemas: {
    ErrorResponse: {
      message: string;
    };
    LineHighlight: {
      column: number;
      term: string;
    };
    LineMatch: {
      content: string;
      highlights: components["schemas"]["LineHighlight"][];
      line_number: number;
    };
    MatchDetail: {
      commit_date: string;
      commit_index: number;
      commit_sha: string;
      commit_summary: string;
      lines: components["schemas"]["LineMatch"][];
    };
    SearchHit: {
      file_path: string;
      first_match: components["schemas"]["MatchDetail"];
      last_match?: components["schemas"]["MatchDetail"] | null;
    };
    SearchMode: "plain" | "regex";
    SearchRequest: {
      limit?: number | null;
      mode?: components["schemas"]["SearchMode"];
      query: string;
    };
    SearchResponse: {
      results: components["schemas"]["SearchHit"][];
    };
  };
};

export type operations = Record<string, never>;

export type external = Record<string, never>;

// Re-export individual schema types for ease of use.
export type ErrorResponse = components["schemas"]["ErrorResponse"];
export type LineHighlight = components["schemas"]["LineHighlight"];
export type LineMatch = components["schemas"]["LineMatch"];
export type MatchDetail = components["schemas"]["MatchDetail"];
export type SearchHit = components["schemas"]["SearchHit"];
export type SearchMode = components["schemas"]["SearchMode"];
export type SearchRequest = components["schemas"]["SearchRequest"];
export type SearchResponse = components["schemas"]["SearchResponse"];
